// Automatic FlutterFlow imports
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import 'index.dart'; // Imports other custom actions
import 'package:flutter/material.dart';
// Begin custom action code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!

import 'index.dart'; // Imports other custom actions

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:super_library/custom_code/actions/super_library.dart';

/// Report a user
/// `reporteeUid` - The UID of the user being reported
/// `type` - The type of report (e.g. 'spam', 'inappropriate', etc.)
/// `reason` - The reason for the report
/// `summary` - A summary of the report
/// `reporter` - The UID of the user reporting the user
/// `createdAt` - The timestamp of the report
/// `path` - The path to the report. This is a unique identifier for the report.
///
/// `path` is automatically generated by the function. To lessen the possibilty of getting errors
/// and the FlutterFlow Developers does not need to worry about making the `path`. They will just
/// need to pass the `reporteeUid` and `type` and the function will handle the rest.
///
/// The same as the `reportExists` function
///
Future report(
  String reporteeUid,
  String type,
  String summary,
  String reason,
) async {
  final data = {
    'reporter': myUid,
    'reportee': reporteeUid,
    'reason': reason,
    'path': '$myUid-$type/$reporteeUid',
    'type': type,
    'summary': summary,
    'createdAt': Timestamp.now()
  };

  /// Set to firestore
  await Report.col.add(data);
}
